// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("back.Model.ForbiddenWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ForbiddenWords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Word = "lorem"
                        },
                        new
                        {
                            Id = 2,
                            Word = "test"
                        },
                        new
                        {
                            Id = 3,
                            Word = "sample"
                        });
                });

            modelBuilder.Entity("back.Model.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Terms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 5, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The biochemical process by which plants convert sunlight, water, and carbon dioxide into oxygen and energy-rich sugars.",
                            Name = "photosynthesis",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 26, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A biological process in which an organism undergoes a distinct physical change after birth or hatching.",
                            Name = "metamorphosis",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 28, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The scientific theory explaining the movement of Earth's lithospheric plates and the geological events that result from their interactions.",
                            Name = "plate tectonics",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 29, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The variety of plant and animal life in a particular habitat, ecosystem, or across the entire planet.",
                            Name = "biodiversity",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 28, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The process by which a liquid transforms into a gas, typically occurring at the surface of the liquid.",
                            Name = "evaporation",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 13, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A chemical reaction in which a substance loses electrons, often associated with the interaction of oxygen with other materials.",
                            Name = "oxidation",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A cellular process in which a single cell divides to produce two genetically identical daughter cells.",
                            Name = "mitosis",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 11, 22, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A community of organisms interacting with one another and with their physical environment as a functioning system.",
                            Name = "ecosystem",
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 20, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The natural force that attracts objects with mass toward one another, most noticeably toward the center of Earth.",
                            Name = "gravity",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 31, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The process by which soil, rock, or other surface material is gradually worn away by wind, water, or ice.",
                            Name = "erosion",
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 10, 2, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A nuclear reaction in which atomic nuclei combine to form a heavier nucleus, releasing significant energy.",
                            Name = "fusion",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 24, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A nuclear reaction in which an atomic nucleus splits into smaller nuclei, releasing energy and particles.",
                            Name = "fission",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 9, 28, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A substance that increases the rate of a chemical reaction without being consumed by the reaction itself.",
                            Name = "catalyst",
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 28, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A protein produced by the immune system that identifies and neutralizes foreign substances such as bacteria or viruses.",
                            Name = "antibody",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 10, 10, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A precise, step-by-step set of instructions used to solve a problem or perform a computation.",
                            Name = "algorithm",
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 10, 21, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The process of converting information into a coded form to prevent unauthorized access.",
                            Name = "encryption",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 10, 5, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A software tool that translates source code written in high-level languages into executable machine code.",
                            Name = "compiler",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 8, 23, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The delivery of computing services, including storage and processing power, over the internet on-demand.",
                            Name = "cloud computing",
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 9, 25, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The maximum amount of data that can be transmitted over a network connection in a given amount of time.",
                            Name = "bandwidth",
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 10, 4, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A computing paradigm that uses quantum-mechanical phenomena to perform calculations far more efficiently for certain classes of problems.",
                            Name = "quantum computing",
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 9, 30, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A branch of artificial intelligence allowing systems to learn patterns from data and make decisions with minimal human intervention.",
                            Name = "machine learning",
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 10, 17, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A computational model inspired by the human brain, composed of interconnected nodes that process information.",
                            Name = "neural network",
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 8, 30, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The visible surface layer of the sun that emits most of its light and radiation.",
                            Name = "photosphere",
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 10, 25, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The scientific study of life in the universe, including its origins, evolution, and possible extraterrestrial existence.",
                            Name = "astrobiology",
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 11, 8, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The atmospheric layer above the troposphere characterized by stable temperatures and the presence of the ozone layer.",
                            Name = "stratosphere",
                            Status = 0
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 10, 7, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A geological process in which Earth's crust rises due to structural forces within the mantle.",
                            Name = "tectonic uplift",
                            Status = 0
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 9, 26, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The natural accumulation of particles transported by wind, water, or ice, forming layers of sediment.",
                            Name = "sedimentation",
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 10, 8, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The gradual movement of Earth's continents over geological time due to plate tectonic processes.",
                            Name = "continental drift",
                            Status = 0
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 11, 15, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A stellar explosion that occurs during the final evolutionary stages of a massive star, producing an extremely bright burst of energy.",
                            Name = "supernova",
                            Status = 0
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 11, 15, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A vast cloud of gas and dust in space, often serving as a region where new stars are formed.",
                            Name = "nebula",
                            Status = 0
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 9, 8, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The luminous outer layer of a star from which its light is radiated into space.",
                            Name = "photosphere",
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 10, 25, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The rigid outer shell of Earth, composed of the crust and the upper mantle.",
                            Name = "lithosphere",
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 11, 13, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "All regions of Earth where life exists, encompassing land, water, and air.",
                            Name = "biosphere",
                            Status = 0
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 11, 11, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A DNA-containing structure within cells that carries genetic information in the form of genes.",
                            Name = "chromosome",
                            Status = 0
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 8, 19, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A foreign substance that triggers an immune system response when detected in the body.",
                            Name = "antigen",
                            Status = 0
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 8, 30, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The movement of particles from an area of higher concentration to an area of lower concentration.",
                            Name = "diffusion",
                            Status = 0
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 10, 4, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The diffusion of water across a semipermeable membrane from a region of low solute concentration to high solute concentration.",
                            Name = "osmosis",
                            Status = 0
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 9, 22, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The mixture of gases surrounding a planet, held in place by gravitational forces.",
                            Name = "atmosphere",
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 9, 29, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A large, slow-moving mass of ice formed from compacted layers of snow over long periods.",
                            Name = "glacier",
                            Status = 0
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 9, 3, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "Any form of water, such as rain, snow, or hail, that falls from the atmosphere to Earth's surface.",
                            Name = "precipitation",
                            Status = 0
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 10, 11, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "Thermal energy generated within Earth that can be harnessed for heating or electricity.",
                            Name = "geothermal energy",
                            Status = 0
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 9, 29, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "Energy collected from resources that replenish naturally, such as solar or wind power.",
                            Name = "renewable energy",
                            Status = 0
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 10, 11, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The natural series of processes by which carbon moves between the atmosphere, oceans, soil, and living organisms.",
                            Name = "carbon cycle",
                            Status = 0
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2025, 11, 12, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "All the water found on, under, and above the surface of a planet.",
                            Name = "hydrosphere",
                            Status = 0
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 9, 26, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A chemical reaction that absorbs heat from its surroundings as it proceeds.",
                            Name = "endothermic reaction",
                            Status = 0
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2025, 10, 24, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A chemical reaction that releases energy in the form of heat or light.",
                            Name = "exothermic reaction",
                            Status = 0
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 9, 30, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A type of rock formed through the cooling and solidification of molten magma or lava.",
                            Name = "igneous rock",
                            Status = 0
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 9, 7, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A rock type formed from compressed layers of sediment over long geological periods.",
                            Name = "sedimentary rock",
                            Status = 0
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 9, 21, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A rock that has been transformed from an existing type through heat, pressure, or chemically active fluids.",
                            Name = "metamorphic rock",
                            Status = 0
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2025, 11, 8, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A historical scientific concept once believed to explain the propagation of light through a universal medium.",
                            Name = "ether theory",
                            Status = 2
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2025, 11, 16, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A defunct scientific theory that proposed the existence of a fire-like element released during combustion.",
                            Name = "phlogiston",
                            Status = 2
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2025, 11, 12, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A superseded hypothesis that claimed empty space was filled with a medium through which light waves traveled.",
                            Name = "luminiferous ether",
                            Status = 2
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2025, 11, 12, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "An outdated belief that living organisms are fundamentally different from non-living entities due to a vital force.",
                            Name = "vitalism",
                            Status = 2
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2025, 11, 11, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A physical phenomenon where particles remain interconnected such that the state of one instantly influences the other.",
                            Name = "quantum entanglement",
                            Status = 1
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2025, 11, 9, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "A form of matter thought to account for most of the mass in the universe, detectable through its gravitational effects.",
                            Name = "dark matter",
                            Status = 1
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2025, 11, 10, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "All of Earth's frozen water, including glaciers, sea ice, and permafrost regions.",
                            Name = "cryosphere",
                            Status = 1
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2025, 11, 10, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The ratio of captured solar energy to biomass produced by photosynthetic organisms.",
                            Name = "photosynthetic efficiency",
                            Status = 1
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2025, 11, 7, 20, 17, 42, 734, DateTimeKind.Utc).AddTicks(3948),
                            CreatedById = 1,
                            Definition = "The production of visible light by living organisms through chemical reactions within their bodies.",
                            Name = "bioluminescence",
                            Status = 1
                        });
                });

            modelBuilder.Entity("back.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "bob@mail.com",
                            Name = "Bob",
                            Password = "123",
                            Role = 1,
                            Surname = "Ross"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ross@mail.com",
                            Name = "Rob",
                            Password = "123",
                            Role = 0,
                            Surname = "Boss"
                        });
                });

            modelBuilder.Entity("back.Model.Term", b =>
                {
                    b.HasOne("back.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
